name: proxy-mgmt-app
version: "0"
synopsis: Proxy conf management
description: Proxy conf management
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-rpo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - aeson-compat
    - base-compat
    - env-config
    - futurice-foundation
    - futurice-prelude
    - futurice-reports
    - futurice-servant
    - generics-sop
    - lucid
    - planmill-client
    - postgresql-simple
    - resource-pool
    - servant
    - servant-lucid
    - servant-server
    - swagger2
    - time
    - vector


executables:
  proxy-mgmt-app-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - proxy-mgmt-app
