name: contacts-api
version: "0"
synopsis: Contacts api
description: New and fancy
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/contacts-api
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

when:
  condition: impl(ghc >= 8.0)
  then:
    ghc-options: -freduction-depth=30
  else:
    ghc-options: -fcontext-stack=30

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - aeson-compat
    - base-compat
    - bifunctors
    - binary-orphans
    - binary-tagged
    - bytestring
    - cassava
    - containers
    - cryptohash
    - deepseq
    - directory
    - env-config
    - exceptions
    - file-embed
    - filepath
    - flowdock-rest
    - fum-client
    - futurice-integrations
    - futurice-prelude
    - futurice-servant
    - futurice-tribes
    - github
    - github
    - hashable
    - haxl
    - haxl-fxtra
    - http-client
    - http-client-tls
    - http-types
    - JuicyPixels
    - JuicyPixels-scale-dct
    - lens
    - lucid
    - mtl
    - parallel-io
    - periocron
    - personio-client
    - planmill-client
    - rfc5051
    - semigroups
    - servant
    - servant-cassava
    - servant-lucid
    - servant-server
    - SHA
    - stm
    - stm-containers
    - strict-base-types >=0.4
    - swagger2
    - tagged
    - text
    - time
    - transformers
    - transformers-compat
    - unordered-containers
    - vector
    - wai

executables:
  contacts-api-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - contacts-api
