name: contacts
version: 0.1.0.0
synopsis: Contacts api
description: New and fancy
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/contacts-api
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall  -fcontext-stack=30

flags:
  aeson-compat:
    manual: True
    default: True

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson                 >=0.8   && <0.12
    - base-compat
    - bifunctors
    - binary-orphans
    - binary-tagged
    - bytestring
    - containers
    - cryptohash
    - deepseq
    - directory
    - env-config
    - exceptions
    - file-embed >=0.0.9
    - filepath
    - flowdock-rest >=0.2
    - fum-client
    - futulogo
    - futurice-integrations
    - futurice-prelude
    - github >= 0.14
    - gitrev
    - hashable
    - haxl                  >=0.3   && <0.4
    - haxl-fxtra
    - haxl-typed
    - http-client           >=0.4   && <0.5
    - http-client-tls       >=0.2.2 && <0.3
    - http-types
    - JuicyPixels
    - JuicyPixels-scale-dct
    - lens
    - lucid
    - mtl
    - parallel-io
    - rfc5051
    - semigroups
    - servant >=0.6 && <0.8
    - servant-cache
    - servant-docs
    - servant-JuicyPixels
    - servant-lucid
    - servant-server
    - servant-status
    - SHA
    - stm
    - stm-containers
    - strict-base-types >=0.4
    - tagged
    - text                  >=1.2   && <1.3
    - time
    - transformers
    - transformers-compat
    - unordered-containers
    - vector                >=0.10  && <0.12
    - wai
    - warp

  when:
    - condition: flag(aeson-compat)
      dependencies:
      - aeson-compat >=0.3.0.0 && <0.4
    - condition: "!flag(aeson-compat)"
      dependencies:
      - aeson-extra  >=0.2.2.0 && <0.3

executables:
  contacts-server:
    ghc-options: -threaded
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - contacts
