name: futurice-foundation
version: "0"
synopsis: Futurice ZURB Foundation helpers
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - clay
    - file-embed
    - futurice-prelude
    - language-javascript >= 0.6.0.8 && <0.7 # For embedJS
    - lens
    - lucid
    - swagger2
    - template-haskell
    - text
