name: futurice-foundation
version: "0"
synopsis: Futurice ZURB Foundation helpers
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  other-modules: []
  dependencies:
    - base                  >=4.7   && <4.11
    - clay
    - file-embed
    - fum-types
    - futurice-prelude
    - futurice-tribes
    - generics-sop
    - generics-sop-lens
    - language-javascript >= 0.6.0.8 && <0.7 # For embedJS
    - lens
    - lucid
    - servant-server
    - servant-swagger-ui
    - swagger2
    - template-haskell
    - text
    - wai-app-static
