name: github-proxy
version: "0"
synopsis: GitHub proxy
description: New and fancy
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

when:
  condition: impl(ghc >= 8.0)
  then:
    ghc-options: -freduction-depth=30
  else:
    ghc-options: -fcontext-stack=30

dependencies:
  - base >=4.7   && <4.11
  - constraints
  - env-config
  - futurice-github
  - futurice-prelude
  - futurice-integrations
  - github
  - http-client
  - http-client-tls
  - intervals
  - operational
  - time-parsers >=0.1.1.0

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - aeson
    - binary
    - binary-tagged
    - bytestring
    - containers
    - exceptions
    - futurice-servant
    - intervals
    - lens
    - monad-logger
    - periocron
    - postgresql-simple
    - postgresql-simple-url
    - resource-pool
    - servant
    - servant-binary-tagged
    - servant-server
    - swagger2
    - text
    - time
    - unordered-containers
    - vector

executables:
  github-proxy-client:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: cli
    dependencies:
      - haxl

  github-proxy-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
     - github-proxy
