sudo: false
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - .stack-work
  - $HOME/.local/bin

before_install:
# Cache name
- CACHE_NAME=$GHCVER
# job starting moment
- JOB_START_TIME=$(date +%s)
# git submodules
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init
# path
- export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- if [ ! -e ~/.local/bin/stack ]; then
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    travis_retry curl -L http://oleg.fi/stack.xz | xz -d > ~/.local/bin/stack;
  fi
# Version infos
- stack +RTS -N1 -RTS --version
- ghc --version
- du -hs .stack-work/

install:
- JOB_CURR_TIME=$(date +%s)
- echo time to run $((JOB_START_TIME + 2400 - JOB_CURR_TIME))
- timeout $((JOB_START_TIME + 2400 - JOB_CURR_TIME)) stack +RTS -N2 -RTS --no-terminal --system-ghc --skip-ghc-check build --test --only-dependencies -j2 --ghc-options="-optl-fuse-ld=gold -j +RTS -M1.5G -A128M -n2m -RTS" || true;

script:
- if [ "$PEDANTIC" = "YES" ]; then export STACKOPTS=--pedantic; fi
- JOB_CURR_TIME=$(date +%s)
- echo time to run $((JOB_START_TIME + 2400 - JOB_CURR_TIME))
- timeout $((JOB_START_TIME + 2400 - JOB_CURR_TIME)) stack +RTS -N2 -RTS --no-terminal --system-ghc --skip-ghc-check build --test $STACKOPTS -j1 --ghc-options="-optl-fuse-ld=gold -j2 +RTS -M2G -A128M -n2m -RTS"
  # - stack --no-terminal --skip-ghc-check sdist

matrix:
  fast_finish: true
  include:
  - env: GHCVER=7.10.3 STACK_YAML=stack-lts-6.yaml PEDANTIC=YES
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - libfftw3-dev
        - alex-3.1.7
        - happy-1.19.5
        - ghc-7.10.3
        - libgmp-dev
  - env: GHCVER=8.0.2 STACK_YAML=stack-ghc-8.0.yaml PEDANTIC=YES
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - libfftw3-dev
        - alex-3.1.7
        - happy-1.19.5
        - ghc-7.10.3
        - ghc-8.0.2
        - libgmp-dev

# Build only master (and PRs to master)
branches:
  only:
  - master

# Because we have to make some sed magic
git:
  submodules: false
