language: haskell-stack

git:
  submodules: false

meta:
  pre:
    before_install:
      - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
      - git submodule update --init

env:
  - GHCVER=7.10.3 STACK_YAML=stack-lts-6.yaml
    # PEDANTIC=YES
  - GHCVER=8.0.1 STACK_YAML=stack-ghc-8.0.yaml

addons:
  apt:
    packages:
      - libfftw3-dev

matrix:
  fast_finish: true

branches:
  only:
    - master
