resolver: ghc-8.6.5
packages:
- arcola/
- avatar-app/
- avatar-client/
- badge-app/
- checklist-app/
- contacts-api/
- dynmap-cache/
- email-proxy-client/
- email-proxy/
- env-config/
- flowdock-grep/
- flowdock-proxy/
- flowdock-rest/
- fum-api/
- fum-carbon-app/
- fum-client/
- fum-types/
- futuqu/
- futurice-chart/
- futurice-constants/
- futurice-croned/
- futurice-foundation/
- futurice-github/
- futurice-integrations/
- futurice-lambda/
- futurice-logo/
- futurice-metrics/
- futurice-postgres/
- futurice-prelude/
- futurice-pure-trans/
- futurice-reports/
- futurice-servant/
- futurice-signed/
- futurice-tribes/
- futuroom-app/
- github-proxy/
- github-sync/
- google-client/
- haxl-fxtra/
- hc-app/
- hours-api/
- lambdacss/
- library-app/
- log-cloudwatch/
- mega-repo-tool/
- monad-memoize/
- okta-client/
- optparse-sop/
- periocron/
- personio-client/
- personio-proxy/
- planmill-client/
- planmill-proxy/
- planmill-sync/
- power-client/
- preferences-app/
- preferences-client/
- proxy-app/
- proxy-mgmt-app/
- proxy-types/
- reports-app/
- servant-Chart/
- servant-algebraic-graphs/
- servant-binary-tagged/
- servant-cached/
- servant-dashdo/
- sisosota-app/
- sisosota-client/
- smileys-app/
- sms-proxy-client/
- sms-proxy/
- theme-app/
- vendor/amazonka/amazonka
- vendor/chart/chart
- vendor/chart/chart-diagrams
- vendor/diffusionkinetics-open/dashdo
- vendor/diffusionkinetics-open/lucid-extras
- vendor/diffusionkinetics-open/plotlyhs
- vendor/monad-http/
extra-deps:
- DRBG-0.5.5
- FontyFruity-0.5.3.4
- HUnit-1.6.0.0
- JuicyPixels-3.3.3
- JuicyPixels-extra-0.4.0
- JuicyPixels-scale-dct-0.1.2
- ListLike-4.6
- MemoTrie-0.6.9
- MonadRandom-0.5.1.1
- Only-0.1
- QuickCheck-2.12.6.1
- Rasterific-0.7.4.2
- SHA-1.6.4.4
- SVGFonts-1.7.0.1
- StateVar-1.1.1.1
- active-0.2.0.13
- adjunctions-4.4
- aeson-1.4.3.0
- aeson-compat-0.3.9
- aeson-extra-0.4.1.1
- aeson-pretty-0.8.7
- alex-3.2.4
- algebraic-graphs-0.2
- amazonka-cloudwatch-1.6.0
- amazonka-cloudwatch-logs-1.6.0
- amazonka-core-1.6.0
- amazonka-lambda-1.6.0
- amazonka-s3-1.6.0
- amazonka-ses-1.6.0
- amazonka-sns-1.6.0
- amazonka-sqs-1.6.0
- ansi-pretty-0.1.2.1
- ansi-terminal-0.8.2
- ansi-wl-pprint-0.6.8.2
- appar-0.1.7
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.2.1
- attoparsec-0.13.2.2
- attoparsec-iso8601-1.0.1.0
- auto-update-0.1.4.1
- aws-lambda-runtime-0
- base-compat-0.10.5
- base-compat-batteries-0.10.5
- base-orphans-0.8
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.2
- base64-bytestring-type-1.0.1
- basement-0.0.10
- bifunctors-5.5.4
- binary-orphans-0.1.8.0
- binary-tagged-0.1.5.1
- bitarray-0.0.1.1
- blaze-builder-0.4.1.0
- blaze-html-0.9.1.1
- blaze-markup-0.8.2.2
- blaze-svg-0.3.6.1
- bsb-http-chunked-0.0.0.4
- byteable-0.1.1
- byteorder-1.0.4
- bytes-0.15.5
- bytestring-builder-0.10.8.2.0
- bytestring-conversion-0.3.1
- cabal-doctest-1.0.6
- cabal-plan-0.5.0.0
- call-stack-0.1.0
- carray-0.1.6.8
- case-insensitive-1.2.0.11
- cassava-0.5.1.0
- cborg-0.2.1.0
- cereal-0.5.8.0
- cereal-vector-0.2.0.1
- charset-0.3.7.1
- chunked-data-0.3.1
- cipher-aes128-0.7.0.4
- clay-0.13.1
- clock-0.7.2
- cmark-gfm-0.2.0
- cmdargs-0.10.20
- colour-2.3.4
- comonad-5.0.4
- composition-1.0.2.1
- composition-extra-2.0.0
- conduit-1.3.1.1
- conduit-extra-1.3.1.1
- connection-0.3.0
- constraints-0.10.1
- contravariant-1.5
- control-monad-omega-0.3.1
- cookie-0.4.4
- crypt-sha512-0
- crypto-api-0.13.3
- cryptohash-0.11.9
- cryptohash-cryptoapi-0.1.4
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- cryptohash-sha256-0.11.101.0
- cryptohash-sha512-0.11.100.1
- cryptonite-0.25
- css-text-0.1.3.0
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- data-reify-0.6.1
- deepseq-generics-0.2.0.0
- dependent-map-0.2.4.0
- dependent-sum-0.4
- deriving-compat-0.5.5
- diagrams-core-1.4.1.1
- diagrams-lib-1.4.2.3
- diagrams-postscript-1.4.1
- diagrams-rasterific-1.4.1.1
- diagrams-solve-0.1.1
- diagrams-svg-1.4.2
- digest-0.0.1.2
- distributive-0.6
- dlist-0.8.0.6
- double-conversion-2.0.2.0
- dual-tree-0.2.2
- easy-file-0.2.2
- ed25519-0.0.5.0
- enclosed-exceptions-1.0.3
- entropy-0.4.1.4
- erf-2.0.0.0
- errors-2.3.0
- exceptions-0.10.1
- extensible-exceptions-0.1.1.4
- extra-1.6.15
- fail-4.9.0.0
- fast-logger-2.4.11
- fft-0.1.8.6
- file-embed-0.0.11
- file-embed-lzma-0
- fin-0.0.2
- fingertree-0.1.4.2
- fmlist-0.9.2
- folds-0.7.4
- free-5.1
- fsnotify-0.3.0.1
- generic-deriving-1.12.4
- generics-sop-0.4.0.1
- generics-sop-lens-0.1.2.1
- github-0.20
- gitrev-1.3.1
- gogol-0.4.0
- gogol-admin-directory-0.4.0
- gogol-apps-calendar-0.4.0
- gogol-core-0.4.0
- gogol-people-0.4.0
- groups-0.4.1.0
- half-0.3
- happy-1.19.9
- hashable-1.2.7.0
- hashable-time-0.2.0.2
- haxl-2.0.1.1
- hinotify-0.4
- hourglass-0.2.12
- hsc2hs-0.68.4
- hspec-2.7.0
- hspec-core-2.7.0
- hspec-discover-2.7.0
- hspec-expectations-0.8.2
- http-api-data-0.4
- http-client-0.5.14
- http-client-tls-0.3.5.3
- http-conduit-2.3.7
- http-date-0.0.8
- http-link-header-1.0.3.1
- http-media-0.7.1.3
- http-types-0.12.3
- http2-1.6.5
- ini-0.4.1
- insert-ordered-containers-0.2.1.0
- integer-logarithms-1.0.3
- intervals-0.8.1
- invariant-0.5.2
- iproute-1.7.7
- iso8601-time-0.1.5
- ix-shapable-0.1.0
- kan-extensions-5.2
- keys-3.12.1
- kleene-0.1
- language-javascript-0.6.0.11
- lattices-2
- lens-4.17.1
- lens-aeson-1.0.2
- libyaml-0.1.1.0
- lifted-async-0.10.0.3
- lifted-base-0.2.3.12
- linear-1.20.8
- log-base-0.7.4.0
- lucid-2.9.11
- lzma-0.0.0.3
- machines-0.6.4
- machines-directory-0.2.1.0
- machines-io-0.2.0.13
- memory-0.14.18
- microlens-0.4.10
- microlens-mtl-0.1.11.1
- microlens-th-0.4.2.3
- microstache-1.0.1.1
- mime-types-0.1.0.9
- mmorph-1.1.2
- monad-control-1.0.2.3
- monad-logger-0.3.30
- monad-loops-0.4.3
- monad-time-0.3.1.0
- monadcryptorandom-0.7.2.1
- mono-traversable-1.0.11.0
- monoid-extras-0.5
- mutable-containers-0.3.4
- nats-1.1.2
- natural-transformation-0.4
- network-3.0.1.1
- network-byte-order-0.0.0.0
- network-info-0.2.0.10
- network-uri-2.6.1.0
- newtype-generics-0.5.3
- nf-1.0.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- operational-0.2.3.5
- optparse-applicative-0.14.3.0
- parallel-3.2.2.0
- parallel-io-0.3.3
- parsers-0.12.9
- path-0.6.1
- pem-0.2.4
- pointed-5.0.1
- postgresql-libpq-0.9.4.2
- postgresql-simple-0.6.2
- postgresql-simple-url-0.2.1.0
- pretty-compact-3.0
- prettyclass-1.0.0.0
- primitive-0.6.4.0
- process-extras-0.7.4
- profunctors-5.3
- psqueues-0.2.7.1
- quickcheck-instances-0.3.19
- quickcheck-io-0.2.0
- random-1.1
- random-shuffle-0.0.4
- range-set-list-0.1.3
- raw-strings-qq-1.1
- recursion-schemes-5.1.3
- reducers-3.12.3
- reflection-2.1.4
- regex-applicative-0.3.3
- regex-applicative-text-0.1.0.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.2.2
- retry-0.8.0.0
- rfc5051-0.1.0.4
- safe-0.3.17
- safe-exceptions-0.1.7.0
- scientific-0.3.6.2
- scotty-0.11.3
- semigroupoids-5.3.2
- semigroups-0.18.5
- serialise-0.2.1.0
- servant-0.16.0.1
- servant-JuicyPixels-0.3.0.4
- servant-blaze-0.9
- servant-cassava-0.10
- servant-client-0.16
- servant-client-core-0.16
- servant-docs-0.11.3
- servant-foreign-0.15
- servant-lucid-0.9
- servant-multipart-0.11.4
- servant-server-0.16
- servant-swagger-1.1.7
- servant-swagger-ui-0.3.2.3.19.3
- servant-swagger-ui-core-0.3.2
- setenv-0.1.1.3
- shelly-1.8.1
- simple-sendfile-0.2.28
- singleton-bool-0.1.4
- socks-0.6.0
- sop-core-0.4.0.0
- split-0.2.3.3
- statestack-0.2.0.5
- step-function-0.2
- stm-chans-3.0.0.4
- storable-complex-0.2.3.0
- streaming-commons-0.2.1.0
- strict-0.3.2
- strict-base-types-0.6.1
- string-conversions-0.4.0.1
- svg-builder-0.1.1
- swagger2-2.3.1.1
- syb-0.7
- system-fileio-0.3.16.4
- system-filepath-0.4.14
- tagged-0.8.6
- tagsoup-0.14.7
- tar-0.5.1.0
- tasty-1.1.0.4
- tasty-hunit-0.10.0.1
- tasty-quickcheck-0.10
- tdigest-0.2.1
- temporary-1.3
- text-binary-0.2.1.1
- text-containers-0.1.0.0
- text-short-0.1.2
- tf-random-0.5
- th-abstraction-0.2.11.0
- th-lift-0.7.11
- th-lift-instances-0.1.11
- these-0.7.6
- time-locale-compat-0.1.1.5
- time-parsers-0.1.2.1
- tls-1.4.1
- transformers-base-0.4.5.2
- transformers-compat-0.6.4
- tree-diff-0.0.2
- trifecta-2
- typed-process-0.2.4.0
- tz-0.1.3.2
- tzdata-0.1.20190325.0
- unbounded-delays-0.1.1.0
- unicode-transforms-0.3.5
- universe-base-1.1
- universe-reverse-instances-1.1
- unix-compat-0.5.1
- unix-time-0.3.8
- unliftio-core-0.1.2.0
- unordered-containers-0.2.10.0
- utf8-string-1.0.1.1
- uuid-1.3.13
- uuid-types-1.0.3
- vault-0.3.1.2
- vec-0.1.1
- vector-0.12.0.2
- vector-algorithms-0.8.0.1
- vector-binary-instances-0.2.5.1
- vector-instances-3.4
- void-0.7.2
- wai-3.2.2
- wai-app-static-3.1.6.3
- wai-extra-3.0.25
- wai-logger-2.3.2
- warp-3.2.27
- wcwidth-0.0.2
- word8-0.1.3
- writer-cps-mtl-0.1.1.6
- writer-cps-transformers-0.5.6.0
- x509-1.7.5
- x509-store-1.6.7
- x509-system-1.6.6
- x509-validation-1.6.11
- xeno-0.3.5.1
- xml-1.3.14
- xml-conduit-1.8.0.1
- xml-types-0.3.6
- xss-sanitize-0.3.6
- yaml-0.11.0.0
- zip-archive-0.4.1
- zlib-0.6.2
flags:
  DRBG:
    test: false
  JuicyPixels:
    mmap: false
  JuicyPixels-extra:
    dev: false
  MemoTrie:
    examples: false
  QuickCheck:
    templatehaskell: true
  Rasterific:
    embed_linear: true
  SHA:
    exe: false
  aeson:
    bytestring-builder: false
    cffi: false
    developer: false
    fast: false
  aeson-pretty:
    lib-only: false
  alex:
    small_base: true
  amazonka-core:
    old-locale: false
  ansi-terminal:
    example: false
  ansi-wl-pprint:
    example: false
  async:
    bench: false
  attoparsec:
    developer: false
  attoparsec-iso8601:
    developer: false
    fast: false
  base64-bytestring-type:
    cereal: true
    http-api-data: true
    serialise: true
  bifunctors:
    semigroups: true
    tagged: true
  bytes:
    test-doctests: true
  bytestring-builder:
    bytestring_has_builder: true
  cabal-plan:
    _: false
    exe: true
    license-report: false
  cassava:
    bytestring--lt-0_10_4: false
  cborg:
    optimize-gmp: true
  cereal:
    bytestring-builder: false
  cipher-aes128:
    halvm: false
    test: false
  clock:
    llvm: false
  cmark-gfm:
    pkgconfig: false
  cmdargs:
    quotation: true
    testprog: false
  comonad:
    containers: true
    contravariant: true
    distributive: true
    test-doctests: true
  contravariant:
    safe: false
    semigroups: true
    statevar: true
    tagged: true
  crypto-api:
    all_cpolys: false
  cryptohash-sha256:
    exe: false
  cryptonite:
    check_alignment: false
    integer-gmp: true
    old_toolchain_inliner: false
    support_aesni: true
    support_deepseq: true
    support_pclmuldq: false
    support_rdrand: true
    support_sse: false
  data-reify:
    tests: false
  deriving-compat:
    base-4-9: true
    new-functor-classes: true
    template-haskell-2-11: true
  digest:
    bytestring-in-base: false
  distributive:
    semigroups: true
    tagged: true
  double-conversion:
    developer: false
  ed25519:
    no-donna: true
    test-doctests: true
    test-hlint: true
    test-properties: true
  entropy:
    halvm: false
  fft:
    base4: true
    splitbase: true
  folds:
    optimize: true
    test-doctests: true
    test-hlint: true
  generic-deriving:
    base-4-9: true
  gogol-core:
    old-locale: false
  happy:
    small_base: true
  hashable:
    examples: false
    integer-gmp: true
    sse2: true
    sse41: false
  hashable-time:
    old-locale: false
  haxl:
    bench: false
  hsc2hs:
    in-ghc-tree: false
  http-api-data:
    use-text-show: false
  http-client:
    network-uri: true
  http2:
    devel: false
  integer-logarithms:
    check-bounds: false
    integer-gmp: true
  intervals:
    herbie: false
    test-doctests: true
  iso8601-time:
    new-time: true
  lens:
    benchmark-uniplate: false
    dump-splices: false
    inlining: true
    j: false
    old-inline-pragmas: false
    safe: false
    test-doctests: true
    test-hunit: true
    test-properties: true
    test-templates: true
    trustworthy: true
  lens-aeson:
    test-doctests: true
  libyaml:
    no-unicode: false
    system-libyaml: false
  linear:
    herbie: false
    template-haskell: true
  memory:
    support_basement: true
    support_bytestring: true
    support_deepseq: true
    support_foundation: true
  microlens-th:
    inlining: true
  monad-logger:
    template_haskell: true
  monad-loops:
    base4: true
  nats:
    binary: true
    hashable: true
    template-haskell: true
  operational:
    buildexamples: true
  parallel-io:
    benchmark: false
    fuzz: false
    tests: false
  parsers:
    binary: true
  pointed:
    comonad: true
    containers: true
    kan-extensions: true
    semigroupoids: true
    semigroups: true
    stm: true
    tagged: true
    transformers: true
    unordered-containers: true
  postgresql-libpq:
    use-pkg-config: false
  quickcheck-instances:
    bytestring-builder: false
  recursion-schemes:
    template-haskell: true
  reflection:
    slow: false
    template-haskell: true
  regex-base:
    newbase: true
    splitbase: true
  regex-compat:
    newbase: true
    splitbase: true
  regex-posix:
    newbase: true
    splitbase: true
  resource-pool:
    developer: false
  retry:
    lib-werror: false
  rfc5051:
    mkunicodedata: false
  scientific:
    bytestring-builder: false
    integer-simple: false
  semigroupoids:
    comonad: true
    containers: true
    contravariant: true
    distributive: true
    doctests: true
    tagged: true
    unordered-containers: true
  semigroups:
    binary: true
    bytestring: true
    bytestring-builder: false
    containers: true
    deepseq: true
    hashable: true
    tagged: true
    text: true
    transformers: true
    unordered-containers: true
  serialise:
    newtime15: true
  shelly:
    build-examples: false
    lifted: false
  simple-sendfile:
    allow-bsd: true
  streaming-commons:
    use-bytestring-builder: false
  strict:
    split-base: true
  tagged:
    deepseq: true
    transformers: true
  tar:
    old-bytestring: false
    old-time: false
  tasty:
    clock: true
  text-short:
    asserts: false
  time-locale-compat:
    old-locale: false
  tls:
    compat: true
    hans: false
    network: true
  transformers-base:
    orphaninstances: true
  transformers-compat:
    five: false
    five-three: true
    four: false
    generic-deriving: true
    mtl: true
    three: false
    two: false
  tz:
    template-haskell: true
  unicode-transforms:
    dev: false
    has-icu: false
    has-llvm: false
  unix-compat:
    old-time: false
  unordered-containers:
    debug: false
  vault:
    useghc: true
  vector:
    boundschecks: true
    internalchecks: false
    unsafechecks: false
    wall: false
  vector-algorithms:
    bench: true
    boundschecks: true
    internalchecks: false
    llvm: false
    properties: true
    unsafechecks: false
  vector-instances:
    hashable: true
  void:
    safe: false
  wai-app-static:
    print: false
  wai-extra:
    build-example: false
  warp:
    allow-sendfilefd: true
    network-bytestring: false
    warp-debug: false
  wcwidth:
    cli: false
    split-base: true
  xeno:
    libxml2: false
  yaml:
    no-examples: true
    no-exe: true
  zip-archive:
    executable: false
  zlib:
    non-blocking-ffi: false
    pkg-config: false
allow-newer: true
