resolver: ghc-8.2.2
packages:
- ansi-pretty/
- arcola/
- avatar-app/
- checklist-app/
- contacts-api/
- dynmap-cache/
- email-proxy-client/
- email-proxy/
- env-config/
- favicon-app/
- flowdock-grep/
- flowdock-rest/
- fum-api/
- fum-carbon-app/
- fum-client/
- fum-types/
- futurice-constants/
- futurice-foundation/
- futurice-github/
- futurice-integrations/
- futurice-logo/
- futurice-metrics/
- futurice-postgres/
- futurice-prelude/
- futurice-pure-trans/
- futurice-reports/
- futurice-servant/
- futurice-tribes/
- github-proxy/
- github-sync/
- haxl-fxtra/
- hc-app/
- hours-api/
- kleene/
- lambdacss/
- log-cloudwatch/
- mega-repo-tool/
- monad-http/
- optparse-sop/
- periocron/
- personio-client/
- personio-proxy/
- planmill-client/
- planmill-proxy/
- planmill-sync/
- proxy-app/
- proxy-mgmt-app/
- reports-app/
- servant-Chart/
- servant-algebraic-graphs/
- servant-binary-tagged/
- servant-dashdo/
- smileys-app/
- sms-proxy/
- theme-app/
- vendor/diffusionkinetics-open/dashdo
- vendor/diffusionkinetics-open/lucid-extras
- vendor/diffusionkinetics-open/plotlyhs
extra-deps:
- Chart-1.8.3
- Chart-diagrams-1.8.3
- DRBG-0.5.5
- HUnit-1.6.0.0
- JuicyPixels-3.2.9.4
- JuicyPixels-scale-dct-0.1.1.2
- ListLike-4.6
- MemoTrie-0.6.9
- MonadRandom-0.5.1
- OneTuple-0.2.1
- Only-0.1
- QuickCheck-2.11.3
- SHA-1.6.4.2
- SVGFonts-1.6.0.3
- StateVar-1.1.0.4
- active-0.2.0.13
- adjunctions-4.3
- aeson-1.2.4.0
- aeson-compat-0.3.7.1
- aeson-extra-0.4.1.0
- aeson-pretty-0.8.5
- alex-3.2.3
- algebraic-graphs-0.0.5
- amazonka-1.5.0
- amazonka-cloudwatch-1.5.0
- amazonka-cloudwatch-logs-1.5.0
- amazonka-core-1.5.0
- amazonka-ses-1.5.0
- ansi-terminal-0.8.0.1
- ansi-wl-pprint-0.6.8.2
- appar-0.1.4
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.2.1
- attoparsec-0.13.2.2
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-compat-0.9.3
- base-orphans-0.6
- base-prelude-1.2.0.1
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- base64-bytestring-type-1
- basement-0.0.6
- bifunctors-5.5.2
- binary-orphans-0.1.8.0
- binary-tagged-0.1.4.2
- bitarray-0.0.1.1
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.2.0
- blaze-svg-0.3.6.1
- boring-0
- byteable-0.1.1
- byteorder-1.0.4
- bytes-0.15.3
- bytestring-builder-0.10.8.1.0
- bytestring-conversion-0.3.1
- cabal-doctest-1.0.6
- cabal-plan-0.3.0.0
- call-stack-0.1.0
- carray-0.1.6.8
- case-insensitive-1.2.0.10
- cassava-0.5.1.0
- cereal-0.5.5.0
- cereal-vector-0.2.0.1
- charset-0.3.7.1
- chunked-data-0.3.1
- cipher-aes128-0.7.0.3
- clay-0.12.2
- clock-0.7.2
- cmdargs-0.10.20
- code-page-0.1.3
- colour-2.3.4
- comonad-5.0.3
- composition-1.0.2.1
- composition-extra-2.0.0
- conduit-1.2.13
- conduit-extra-1.2.3.2
- connection-0.2.8
- constraints-0.10
- contravariant-1.4.1
- cookie-0.4.3
- crypt-sha512-0
- crypto-api-0.13.3
- cryptohash-0.11.9
- cryptohash-cryptoapi-0.1.4
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- cryptohash-sha512-0.11.100.1
- cryptonite-0.25
- css-text-0.1.3.0
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- data-reify-0.6.1
- deepseq-generics-0.2.0.0
- dependent-map-0.2.4.0
- dependent-sum-0.4
- deriving-compat-0.4.1
- diagrams-core-1.4.0.1
- diagrams-lib-1.4.2
- diagrams-postscript-1.4
- diagrams-solve-0.1.1
- diagrams-svg-1.4.1.1
- distributive-0.5.3
- dlist-0.8.0.4
- doctest-0.13.0
- double-conversion-2.0.2.0
- dual-tree-0.2.1
- easy-file-0.2.1
- either-5
- entropy-0.3.8
- errors-2.2.2
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- extra-1.6.3
- fail-4.9.0.0
- fast-logger-2.4.11
- fft-0.1.8.6
- file-embed-0.0.10.1
- fin-0
- fingertree-0.1.3.1
- fmlist-0.9.2
- focus-0.1.5.2
- folds-0.7.4
- foundation-0.0.19
- free-4.12.4
- friendly-time-0.4.1
- fsnotify-0.2.1.1
- generic-deriving-1.12.1
- generics-sop-0.3.2.0
- generics-sop-lens-0.1.2.1
- ghc-paths-0.1.0.9
- github-0.19
- gitrev-1.3.1
- groups-0.4.1.0
- happy-1.19.9
- hashable-1.2.6.1
- hashable-time-0.2.0.1
- haxl-0.5.1.0
- hinotify-0.3.8.1
- hourglass-0.2.11
- hsc2hs-0.68.2
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- hspec-expectations-0.8.2
- http-api-data-0.3.7.2
- http-client-0.5.10
- http-client-tls-0.3.5.3
- http-conduit-2.2.4
- http-date-0.0.6.1
- http-link-header-1.0.3
- http-media-0.7.1.2
- http-types-0.12.1
- http2-1.6.3
- ini-0.3.5
- insert-ordered-containers-0.2.1.0
- integer-logarithms-1.0.2
- intervals-0.8.1
- iproute-1.7.2
- iso8601-time-0.1.4
- ix-shapable-0.1.0
- kan-extensions-5.1
- keys-3.12
- language-javascript-0.6.0.10
- lattices-1.7.1
- lens-4.16
- lens-aeson-1.0.2
- lifted-async-0.10.0
- lifted-base-0.2.3.11
- linear-1.20.7
- list-t-1.0.0.1
- log-base-0.7.4.0
- lucid-2.9.9
- machines-0.6.3
- machines-directory-0.2.1.0
- machines-io-0.2.0.13
- markdown-0.1.16
- memory-0.14.14
- microlens-0.4.8.3
- microlens-mtl-0.1.11.1
- microlens-th-0.4.1.3
- microstache-1.0.1.1
- mime-types-0.1.0.7
- mmorph-1.1.0
- monad-control-1.0.2.2
- monad-logger-0.3.28.1
- monad-loops-0.4.3
- monad-time-0.2
- monadcryptorandom-0.7.1
- monoid-extras-0.4.2
- mtl-2.2.1
- nats-1.1.2
- natural-transformation-0.4
- network-2.6.3.3
- network-info-0.2.0.9
- network-uri-2.6.1.0
- newtype-generics-0.5.2.1
- nf-1.0.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- operational-0.2.3.5
- optparse-applicative-0.14.0.0
- parallel-3.2.1.1
- parallel-io-0.3.3
- parsec-3.1.13.0
- parsers-0.12.8
- path-0.6.1
- pem-0.2.2
- pointed-5.0.1
- postgresql-libpq-0.9.4.0
- postgresql-simple-0.5.3.0
- postgresql-simple-url-0.2.0.0
- prelude-extras-0.4.0.3
- pretty-compact-3.0
- prettyclass-1.0.0.0
- primitive-0.6.3.0
- process-extras-0.7.4
- profunctors-5.2.2
- psqueues-0.2.5.0
- quickcheck-instances-0.3.16.1
- quickcheck-io-0.2.0
- random-1.1
- random-shuffle-0.0.4
- range-set-list-0.1.2.0
- recursion-schemes-5.0.2
- reducers-3.12.2
- reflection-2.1.3
- regex-applicative-0.3.3
- regex-applicative-text-0.1.0.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.1.11
- retry-0.7.6.0
- rfc5051-0.1.0.3
- safe-0.3.16
- safe-exceptions-0.1.7.0
- scientific-0.3.5.2
- scotty-0.11.0
- semigroupoids-5.2.2
- semigroups-0.18.3
- servant-0.13
- servant-JuicyPixels-0.3.0.3
- servant-blaze-0.8
- servant-cassava-0.10
- servant-client-0.13
- servant-client-core-0.13
- servant-lucid-0.8
- servant-server-0.13
- servant-swagger-1.1.5
- servant-swagger-ui-0.2.5.3.9.1
- setenv-0.1.1.3
- simple-sendfile-0.2.27
- singleton-bool-0.1.3
- socks-0.5.6
- split-0.2.3.3
- statestack-0.2.0.5
- stm-2.4.5.0
- stm-chans-3.0.0.4
- stm-containers-0.2.16
- storable-complex-0.2.2
- streaming-commons-0.1.19
- strict-0.3.2
- strict-base-types-0.6.1
- string-conversions-0.4.0.1
- stringsearch-0.3.6.6
- svg-builder-0.1.0.2
- swagger2-2.2
- syb-0.7
- system-filepath-0.4.14
- tagged-0.8.5
- tagsoup-0.14.3
- tasty-1.0.1
- tasty-hunit-0.10.0.1
- tasty-quickcheck-0.10
- tdigest-0.1
- temporary-1.2.1.1
- text-1.2.3.0
- text-binary-0.2.1.1
- text-short-0.1.1
- tf-random-0.5
- th-abstraction-0.2.6.0
- th-lift-0.7.8
- th-lift-instances-0.1.11
- these-0.7.4
- time-locale-compat-0.1.1.3
- time-parsers-0.1.2.0
- tls-1.4.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- tree-diff-0.0.1
- trifecta-1.7.1.1
- tuple-0.3.0.2
- typed-process-0.2.1.0
- tz-0.1.3.0
- tzdata-0.1.20180122.0
- unbounded-delays-0.1.1.0
- unexceptionalio-0.3.0
- unicode-transforms-0.3.3
- universe-base-1.0.2.1
- universe-instances-base-1.0
- universe-reverse-instances-1.0
- unix-compat-0.5.0.1
- unix-time-0.3.7
- unliftio-core-0.1.1.0
- unordered-containers-0.2.9.0
- uri-bytestring-0.3.1.0
- utf8-string-1.0.1.1
- uuid-1.3.13
- uuid-types-1.0.3
- vault-0.3.1.0
- vec-0
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.4
- vector-instances-3.4
- void-0.7.2
- wai-3.2.1.1
- wai-app-static-3.1.6.1
- wai-extra-3.0.22.0
- wai-logger-2.3.1
- warp-3.2.17
- word8-0.1.3
- writer-cps-mtl-0.1.1.4
- writer-cps-transformers-0.1.1.3
- x509-1.7.2
- x509-store-1.6.5
- x509-system-1.6.6
- x509-validation-1.6.9
- xml-1.3.14
- xml-conduit-1.7.1.2
- xml-types-0.3.6
- xss-sanitize-0.3.5.7
- yaml-0.8.28
- zlib-0.6.1.2
flags:
  DRBG:
    test: false
  JuicyPixels:
    mmap: false
  MemoTrie:
    examples: false
  QuickCheck:
    templatehaskell: true
  SHA:
    exe: false
  aeson:
    bytestring-builder: false
    cffi: false
    developer: false
    fast: false
  aeson-pretty:
    lib-only: false
  alex:
    small_base: true
  amazonka-core:
    old-locale: false
  ansi-terminal:
    example: false
  ansi-wl-pprint:
    example: false
  async:
    bench: false
  attoparsec:
    developer: false
  attoparsec-iso8601:
    developer: false
    fast: false
  avatar-app:
    aeson-compat: true
  bifunctors:
    semigroups: true
    tagged: true
  bytes:
    test-doctests: true
  bytestring-builder:
    bytestring_has_builder: true
  cabal-plan:
    _: false
    exe: false
  cassava:
    bytestring--lt-0_10_4: false
  cereal:
    bytestring-builder: false
  cipher-aes128:
    halvm: false
    test: false
  clock:
    llvm: false
  cmdargs:
    quotation: true
    testprog: false
  comonad:
    containers: true
    contravariant: true
    distributive: true
    test-doctests: true
  contravariant:
    safe: false
    semigroups: true
    statevar: true
    tagged: true
  crypto-api:
    all_cpolys: false
  cryptonite:
    check_alignment: false
    integer-gmp: true
    old_toolchain_inliner: false
    support_aesni: true
    support_deepseq: true
    support_pclmuldq: false
    support_rdrand: true
    support_sse: false
  data-reify:
    tests: false
  deriving-compat:
    base-4-9: true
    new-functor-classes: true
    template-haskell-2-11: true
  distributive:
    semigroups: true
    tagged: true
  double-conversion:
    developer: false
  entropy:
    halvm: false
  fft:
    base4: true
    splitbase: true
  folds:
    optimize: true
    test-doctests: true
    test-hlint: true
  foundation:
    bench-all: false
    bounds-check: false
    doctest: false
    experimental: false
    minimal-deps: false
  generic-deriving:
    base-4-9: true
  github:
    aeson-compat: true
  happy:
    small_base: true
  hashable:
    examples: false
    integer-gmp: true
    sse2: true
    sse41: false
  hashable-time:
    old-locale: false
  http-api-data:
    use-text-show: false
  http-client:
    network-uri: true
  http2:
    devel: false
  integer-logarithms:
    check-bounds: false
    integer-gmp: true
  intervals:
    herbie: false
    test-doctests: true
  iso8601-time:
    new-time: true
  lens:
    benchmark-uniplate: false
    dump-splices: false
    inlining: true
    j: false
    old-inline-pragmas: false
    safe: false
    test-doctests: true
    test-hunit: true
    test-properties: true
    test-templates: true
    trustworthy: true
  lens-aeson:
    test-doctests: true
  linear:
    herbie: false
    template-haskell: true
  memory:
    support_bytestring: true
    support_deepseq: true
    support_foundation: true
  microlens-th:
    inlining: true
  monad-logger:
    template_haskell: true
  monad-loops:
    base4: true
  nats:
    binary: true
    hashable: true
    template-haskell: true
  operational:
    buildexamples: true
  parallel-io:
    benchmark: false
    fuzz: false
    tests: false
  pointed:
    comonad: true
    containers: true
    kan-extensions: true
    semigroupoids: true
    semigroups: true
    stm: true
    tagged: true
    transformers: true
    unordered-containers: true
  postgresql-libpq:
    use-pkg-config: false
  recursion-schemes:
    template-haskell: true
  reflection:
    slow: false
    template-haskell: true
  regex-base:
    newbase: true
    splitbase: true
  regex-compat:
    newbase: true
    splitbase: true
  regex-posix:
    newbase: true
    splitbase: true
  resource-pool:
    developer: false
  retry:
    lib-werror: false
  rfc5051:
    mkunicodedata: false
  scientific:
    bytestring-builder: false
    integer-simple: false
  semigroupoids:
    comonad: true
    containers: true
    contravariant: true
    distributive: true
    doctests: true
    tagged: true
    unordered-containers: true
  semigroups:
    binary: true
    bytestring: true
    bytestring-builder: false
    containers: true
    deepseq: true
    hashable: true
    tagged: true
    text: true
    transformers: true
    unordered-containers: true
  servant-swagger-ui:
    servant-0-5: true
  simple-sendfile:
    allow-bsd: true
  storable-complex:
    instanceinbase: true
  streaming-commons:
    use-bytestring-builder: false
  strict:
    split-base: true
  stringsearch:
    base3: false
    base4: true
  tagged:
    deepseq: true
    transformers: true
  tasty:
    clock: true
  text:
    bytestring-builder: false
    developer: false
    integer-simple: false
  time-locale-compat:
    old-locale: false
  tls:
    compat: true
    hans: false
    network: true
  transformers-base:
    orphaninstances: true
  transformers-compat:
    mtl: true
    three: false
    two: false
  tz:
    template-haskell: true
  unicode-transforms:
    dev: false
    has-icu: false
    has-llvm: false
  unix-compat:
    old-time: false
  unordered-containers:
    debug: false
  uri-bytestring:
    lib-werror: false
  vault:
    useghc: true
  vector:
    boundschecks: true
    internalchecks: false
    unsafechecks: false
    wall: false
  vector-algorithms:
    bench: false
    boundschecks: true
    internalchecks: false
    properties: true
    unsafechecks: false
  vector-instances:
    hashable: true
  void:
    safe: false
  wai-app-static:
    print: false
  wai-extra:
    build-example: false
  warp:
    allow-sendfilefd: true
    network-bytestring: false
    warp-debug: false
  xss-sanitize:
    network-uri: true
  yaml:
    no-examples: true
    no-exe: false
    no-unicode: false
    system-libyaml: false
  zlib:
    non-blocking-ffi: false
allow-newer: true
