name: futurice-pure-trans
version: "0"
synopsis: A reader monad transformer to provide context to IO
description: A reader monad transformer to provide context to IO
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

library:
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - futurice-prelude
    - http-client
    - lens
    - lifted-base
    - log-base
    - monad-http
    - monadcryptorandom
    - resource-pool
    - unordered-containers
