name: github-sync
version: "0"
synopsis: Manage GitHub
description: New and fancy
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

when:
  condition: impl(ghc >= 8.0)
  then:
    ghc-options: -freduction-depth=30
  else:
    ghc-options: -fcontext-stack=30

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  other-modules: []
  dependencies:
    - base                  >=4.7   && <4.11
    - aeson
    - aeson-compat
    - env-config
    - fum-types
    - futurice-foundation
    - futurice-integrations
    - futurice-prelude
    - futurice-servant
    - github
    - haxl
    - lens
    - personio-client
    - regex-applicative
    - servant
    - servant-lucid
    - servant-server

executables:
  github-sync-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - github-sync
