name: reports-app
version: "0"
synopsis: Show various reports.
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.8 && <4.10
  - base-compat
  - aeson
  - aeson-pretty
  - ansi-pretty
  - base64-bytestring
  - bifunctors
  - binary-orphans
  - binary-tagged
  - bytestring
  - case-insensitive
  - cassava
  - constraints
  - containers
  - deepseq
  - directory
  - either
  - env-config
  - exceptions
  - filepath
  - flowdock-rest
  - friendly-time >=0.4 && <0.5
  - fum-client
  - futulogo
  - futurice-foundation
  - futurice-integrations
  - futurice-prelude
  - futurice-reports
  - futurice-servant
  - generics-sop
  - github >=0.15.0
  - hashable >= 1.2
  - http-client >= 0.5 # responseTimeoutMicro
  - http-client-tls
  - http-types
  - intervals
  - lens
  - lucid
  - markdown
  - mtl
  - optparse-applicative
  - periocron
  - planmill-client
  - postgresql-simple
  - postgresql-simple-url
  - regex-applicative
  - regex-applicative-text
  - regex-compat
  - resource-pool
  - semigroups
  - servant
  - servant-cassava ==0.8.*
  - servant-lucid
  - servant-server
  - SHA
  - stm
  - strict-base-types
  - swagger2
  - tagged
  - text
  - these
  - time
  - transformers
  - transformers-compat
  - unordered-containers
  - vector

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables

executables:
  reports-app-server:
    main: Main.hs
    source-dirs: srv
    ghc-options: -Wall -threaded
    dependencies:
      - reports-app 
