name: futurice-postgres
version: "0"
synopsis: Postgres stuff
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==8.0.2, GHC==8.2.1
extra-source-files:
- README.md

ghc-options: -Wall

library:
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
  source-dirs: src
  other-modules: []
  dependencies:
    - base                  >=4.7 && <5
    - aeson-compat
    - exceptions
    - futurice-metrics
    - futurice-prelude
    - postgresql-simple
    - resource-pool
