name: dynmap-cache
version: "0"
synopsis: Dynamic STM based cache
description: Dynamic STM based cache
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base            >=4.7      && <4.10
  - base-compat
  - bytestring
  - async
  - either
  - hashable
  - lens
  - monad-control
  - stm
  - stm-containers
  - tagged
  - time
  - transformers
  - transformers-compat
  - transformers-base
  - list-t
  - futurice-prelude

library:
  source-dirs: src

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts
    dependencies:
      - dynmap-cache
      - tasty
      - tasty-hunit
