name: dynmap-cache
version: "0"
synopsis: Dynamic STM based cache
description: Dynamic STM based cache
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==8.0.2, GHC==8.2.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base            >=4.9      && <4.11
  - async
  - base-compat
  - bytestring
  - deepseq
  - dependent-map
  - dependent-sum
  - either
  - exceptions
  - futurice-prelude
  - hashable
  - log-base
  - monad-control
  - nf
  - stm
  - tagged
  - text
  - time
  - transformers
  - transformers-base
  - transformers-compat
  - unordered-containers

library:
  source-dirs: src
  other-modules: []

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts
    dependencies:
      - dynmap-cache
      - tasty
      - tasty-hunit
