name: mega-repo-tool
version: "0"
synopsis: Various commands to manage futurice/haskell-mega-repo
description: Build the package and run @stack exec mega-repo-tool -- -h@
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-compat
    - aeson-extra
    - base >=4.7   && <4.10
    - base-compat
    - bytestring
    - case-insensitive
    - containers
    - crypto-api
    - entropy
    - exceptions
    - futurice-prelude
    - http-client
    - http-client-tls
    - lens
    - machines           >= 0.6.1
    - machines-directory >= 0.2.1.0 # for directoryWalk'
    - optparse-applicative
    - process
    - regex-applicative
    - regex-applicative-text
    - semigroups
    - tagged
    - tdigest
    - temporary
    - text
    - time
    - transformers
    - unordered-containers
    - vector
    - yaml

executables:
  mega-repo-tool:
    source-dirs: cli
    main: Main.hs
    dependencies:
      - base
      - mega-repo-tool
