name: futurice-logo
version: "0"
synopsis: Generate futurice logo
description: |
  ... and other stuff
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base                  >=4.7      && <4.11
  - futurice-prelude
  - JuicyPixels           >=3.2.7    && <3.3
  - base-compat           >=0.6      && <0.10
  - bytestring            >=0.10.4.0 && <0.11
  - clay
  - deepseq               >=1.3.0.2  && <1.5
  - file-embed            >=0.0.8.2  && <0.0.11
  - hashable              >=1.2.3.3  && <1.3
  - http-media            >=0.6.2    && <0.8
  - servant               >=0.4.4.5  && <0.13
  - servant-server        >=0.4.4.5  && <0.13
  - tagged                >=0.7.3    && <0.9
  - swagger2              >=2.0      && <2.3
  - text
# Actually we need newer:
  - servant-JuicyPixels   >=0.3.0.0  && <0.4

library:
  source-dirs: src
  other-modules: []
