name: email-proxy
version: "0"
synopsis: Email Proxy
description: Make an email-proxy of everything
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - base-compat
    - base64-bytestring
    - bytestring
    - env-config
    - futurice-prelude
    - futurice-servant
    - http-client
    - http-types
    - lens
    - servant-server
    - semigroups
    - SHA
    - text
    - time

executables:
  email-proxy-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - email-proxy
