name: planmill-client
version: "0"
synopsis: PlanMill API
description: |
  Bindings to <https://online.planmill.com/pmtrial/schemas/v1_5/index.html PlanMill API 1.5>.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-planmill-client
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall
       
when:
- condition: impl(ghc >= 8.0)
  ghc-options: -freduction-depth=100
- condition: impl(ghc < 8.0)
  ghc-options: -fcontext-stack=40

dependencies:
  - base >=4.8 && <4.10
  - aeson
  - aeson-compat
  - aeson-extra
  - ansi-pretty
  - ansi-wl-pprint
  - async
  - attoparsec
  - base-compat
  - base64-bytestring
  - binary
  - binary-orphans
  - binary-tagged
  - byteable
  - bytestring
  - cassava
  - composition-extra
  - constraints
  - containers
  - cryptohash
  - deepseq
  - dependent-sum
  - DRBG
  - env-config
  - exceptions
  - futurice-prelude
  - generics-sop
  - hashable
  - hashable-time
  - haxl
  - http-api-data
  - http-client
  - http-client-tls
  - http-types
  - intervals
  - lens
  - log-base
  - monad-http
  - monad-time
  - monadcryptorandom >=0.7.0
  - mtl
  - operational
  - optparse-sop
  - postgresql-simple
  - QuickCheck
  - reflection >= 2 && <2.3
  - regex-applicative-text
  - scientific
  - semigroups
  - singleton-bool >= 0.1.2.0 # We need sboolEqRefl
  - swagger2
  - text
  - time
  - time-locale-compat
  - time-parsers
  - transformers
  - unordered-containers
  - vector

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - planmill-client
      - tasty
      - tasty-quickcheck
      - file-embed
  integration:
    main: Integration.hs
    source-dirs: integration
    dependencies:
      - planmill-client

executables:
  planmill-client:
    main: Main.hs
    source-dirs: cli
    dependencies:
      - planmill-client
      - optparse-applicative
      - SHA
      - yaml

  pm-cli:
    main: Main.hs
    source-dirs: cli2
    dependencies:
      - monad-control
      - planmill-client
      - transformers-base
