name: planmill-sync
version: "0"
synopsis: Manage PlanMill
description: New and fancy
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  other-modules: []
  dependencies:
    - base                  >=4.7   && <4.11
    - aeson
    - aeson-compat
    - env-config
    - fum-types
    - futurice-foundation
    - futurice-integrations
    - futurice-prelude
    - futurice-servant
    - planmill-client
    - haxl
    - lens
    - personio-client
    - regex-applicative
    - regex-applicative-text
    - these
    - servant
    - servant-lucid
    - servant-server

executables:
  planmill-sync-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - planmill-sync
