name: futurice-servant
version: "0"
synopsis: Collection of utilities for servant
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

library:
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - NoImplicitPrelude
    - ScopedTypeVariables
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - base-compat
    - futulogo
    - futurice-prelude
    - gitrev >=1.2.0
    - servant
    - servant-cache
    - servant-lucid
    - servant-server
    - servant-status
    - servant-swagger
    - servant-swagger-ui
    - stm
    - swagger2
    - text
    - wai
    - warp
