name: theme-app
version: "0"
synopsis: Show Futurice colour theme
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.10
  - clay >= 0.11
  - env-config
  - JuicyPixels
  - futulogo
  - futurice-foundation
  - futurice-prelude
  - futurice-servant
  - lucid
  - servant
  - servant-server
  - servant-swagger-ui
  - text
  - wai-app-static
  - warp

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables

executables:
  theme-app-server:
    main: Main.hs
    source-dirs: srv
    ghc-options: -Wall -threaded
    dependencies:
      - theme-app 
