name: futurice-constants
version: "0"
synopsis: Futurice constants
description: Futurice constants
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

dependencies:
  - base            >=4.7      && <4.10
  - aeson-compat
  - containers
  - futurice-prelude
  - lucid
  - QuickCheck
  - swagger2
  - template-haskell
  - text
  - vector

library:
  source-dirs: src
  other-modules:
    - Futurice.Constants.Internal
