name: servant-status
version: "0"
synopsis: Servant status API
description: Servant status API
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-servant-status
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

flags:
  aeson-compat:
    manual: false
    default: true

dependencies:
  - base                  >=4.7      && <4.10
  - base-compat           >=0.6.0    && <0.10
  - hashable              >=1.2.3.3  && <1.3
  - random                >=1.1      && <1.2
  - semigroups            >=0.16.2.2 && <0.19
  - servant               >=0.4.4.5  && <0.10
  - servant-server        >=0.4.4.5  && <0.10
  - text                  >=1.2.0.6  && <1.3
  - time                  >=1.4.2    && <1.7
  - transformers          >=0.3.0.0  && <0.6
  - unordered-containers  >=0.2.5.1  && <0.3

when:
  - condition: flag(aeson-compat)
    dependencies:
    - aeson-compat >=0.3.0.0 && <0.4
  - condition: "!flag(aeson-compat)"
    dependencies:
      - aeson-extra  >=0.2.2.0 && <0.3

library:
  source-dirs: src

tests:
  example:
    main: Main.hs
    source-dirs: example
    ghc-options: -threaded -with-rtsopts=-T
    dependencies:
      - servant-status
      - wai            >=3.0.3.0  && <3.3
      - warp           >=3.0.13.1 && <3.3
