name: fum-client-types
version: "0"
synopsis: FUM client types
description: "In other words: @Login@ type"
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

dependencies:
  - base            >=4.7      && <4.11
  - aeson
  - aeson-compat
  - cassava
  - containers
  - futurice-prelude
  - lucid
  - postgresql-simple
  - QuickCheck
  - swagger2
  - template-haskell
  - text
  - vector

library:
  source-dirs: src
