name: checklist-app
version: "0"
synopsis: Over-engineered TODO
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

dependencies:
  - base >= 4.7 && <4.10
  - adjunctions
  - aeson
  - aeson-compat
  - ansi-pretty
  - ansi-wl-pprint
  - async
  - Chart
  - clay
  - constraints
  - containers
  - crypto-api
  - deepseq
  - distributive
  - DRBG
  - env-config
  - fum-client
  - futurice-foundation
  - futurice-prelude
  - futurice-servant
  - generics-sop
  - generics-sop-lens
  - http-api-data
  - lattices
  - lens
  - lucid
  - mtl
  - postgresql-simple
  - QuickCheck
  - recursion-schemes >= 5.0.1
  - reflection
  - regex-applicative
  - resource-pool
  - servant
  - servant-Chart
  - servant-lucid
  - servant-server
  - singleton-bool
  - split
  - stm
  - swagger2
  - text
  - time
  - trifecta
  - uuid

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables

executables:
  checklist-app-server:
    main: Main.hs
    source-dirs: srv
    ghc-options: -Wall -threaded -rtsopts
    dependencies:
      - checklist-app 

  checklist-import:
    main: Import.hs
    source-dirs: import
    ghc-options: -Wall -threaded -rtsopts
    dependencies:
      - checklist-app 
      - lifted-base
      - transformers
      - yaml

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: tests/
    dependencies:
      - tasty
      - tasty-quickcheck
      - checklist-app
