name: checklist-app
version: "0"
synopsis: Over-engineered TODO
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.11
  - adjunctions
  - aeson
  - aeson-compat
  - ansi-pretty
  - ansi-wl-pprint
  - async
  - Chart
  - clay
  - constraints
  - containers
  - crypto-api
  - DRBG
  - deepseq
  - distributive
  - env-config
  - fum-api
  - fum-types
  - futurice-foundation
  - futurice-integrations
  - futurice-prelude
  - futurice-servant
  - futurice-tribes
  - generics-sop
  - generics-sop-lens
  - http-api-data
  - lattices >=1.6
  - lens
  - lens-aeson
  - lucid
  - mtl
  - periocron
  - personio-client
  - postgresql-simple
  - QuickCheck
  - recursion-schemes >= 5.0.1
  - reflection
  - regex-applicative
  - resource-pool
  - servant
  - servant-Chart
  - servant-lucid
  - servant-server
  - singleton-bool
  - split
  - stm
  - swagger2
  - text
  - time
  - trifecta
  - uuid

library:
  source-dirs: src
  other-modules: []
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables

executables:
  checklist-app-server:
    main: Main.hs
    source-dirs: srv
    ghc-options: -Wall -threaded -rtsopts
    dependencies:
      - checklist-app

  checklist-import:
    main: Import.hs
    source-dirs: import
    ghc-options: -Wall -threaded -rtsopts
    dependencies:
      - checklist-app
      - lifted-base
      - transformers
      - yaml

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: tests/
    dependencies:
      - tasty
      - tasty-quickcheck
      - checklist-app
