name: checklist-app
version: "0"
synopsis: Over-engineered TODO
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.10
  - aeson
  - aeson-compat
  - clay
  - containers
  - env-config
  - fum-client
  - futurice-foundation
  - futurice-prelude
  - futurice-servant
  - lens
  - lucid
  - postgresql-simple
  - QuickCheck
  - servant
  - servant-lucid
  - servant-server
  - generics-sop
  - swagger2
  - text
  - time
  - uuid

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables

executables:
  checklist-app-server:
    main: Main.hs
    source-dirs: srv
    ghc-options: -Wall -threaded
    dependencies:
      - checklist-app 

  checklist-import:
    main: Import.hs
    source-dirs: import
    ghc-options: -Wall -threaded
    dependencies:
      - checklist-app 
      - transformers
      - yaml

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: tests/
    dependencies:
      - tasty
      - tasty-quickcheck
      - checklist-app
