name: proxy-app
version: "0"
synopsis: Proxy app
description: Make a proxy of everything
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/proxy-app
category: Web
tested-with: GHC==8.0.2, GHC==8.2.1
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  other-modules: []
  dependencies:
    - base                  >=4.7   && <4.11
    - aeson
    - aeson-compat
    - base-compat
    - bifunctors
    - blaze-html
    - bytestring
    - cassava
    - containers
    - env-config
    - fum-api
    - fum-client
    - futurice-github
    - futurice-metrics
    - futurice-prelude
    - futurice-servant
    - http-client
    - http-client-tls
    - http-media
    - lens
    - markdown
    - personio-client
    - planmill-client
    - postgresql-simple
    - reflection
    - regex-applicative
    - regex-applicative-text
    - reports-app
    - resource-pool
    - semigroups
    - servant
    - servant-binary-tagged
    - servant-cassava
    - servant-client
    - servant-client-core
    - servant-lucid
    - servant-server
    - servant-swagger
    - stm
    - swagger2
    - tagged
    - text
    - time
    - transformers
    - unordered-containers
    - vector
    - wai
    - wai-extra >=3.0.19 # basicAuth'
    - warp

executables:
  proxy-app-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - proxy-app

tests:
  proxy-app-tests:
    main: Tests.hs
    source-dirs: tests/
    dependencies:
      - base
      - binary-tagged
      - base16-bytestring
      - futurice-github
      - futurice-prelude
      - planmill-client
      - tasty
      - tasty-quickcheck
