name: futurice-integrations
version: "0"
synopsis: Tools to work uniformly with different integrations
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - async
    - binary-tagged
    - bytestring
    - cassava
    - constraints
    - containers
    - env-config
    - flowdock-rest
    - fum-client
    - futurice-github
    - futurice-prelude
    - futurice-reports
    - generics-sop
    - generics-sop-lens
    - github
    - haxl
    - haxl-fxtra
    - http-client
    - http-client-tls
    - intervals
    - lens
    - lucid
    - monad-logger
    - monad-time
    - planmill-client
    - regex-applicative-text
    - text
    - time
    - transformers
    - tz
    - unordered-containers
    - vector
    - zlib
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
