name: futurice-integrations
version: "0"
synopsis: Tools to work uniformly with different integrations
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - bytestring
    - cassava
    - constraints
    - containers
    - flowdock-rest
    - fum-client
    - futurice-prelude
    - futurice-reports
    - github
    - haxl
    - haxl-fxtra
    - http-client
    - lens
    - lucid
    - monad-logger
    - monad-time
    - planmill-client
    - regex-applicative-text
    - text
    - time
    - transformers
    - tz
    - unordered-containers
    - vector
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
