name: avatar-app
version: "0"
synopsis: Avatar app
description: Make an avatar of everything
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/avatar-app
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

flags:
  aeson-compat:
    manual: True
    default: True

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - base-compat
    - blaze-html
    - bytestring
    - either
    - env-config
    - futulogo
    - futurice-prelude
    - futurice-servant
    - http-client
    - http-client-tls
    - JuicyPixels >=3.2.7
    - JuicyPixels-scale-dct >=0.1.0.0
    - lens
    - markdown
    - semigroups
    - servant
    - servant-JuicyPixels >=0.3.0.0
    - servant-server
    - stm
    - text
    - time
    - transformers
    - transformers-compat
    - unordered-containers
    - vector

  when:
    - condition: flag(aeson-compat)
      dependencies:
        - aeson-compat >=0.3.0.0 && <0.4
    - condition: "!flag(aeson-compat)"
      dependencies:
        - aeson-extra  >=0.2.2.0 && <0.3

executables:
  avatar-server:
    ghc-options: -threaded
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - avatar-app
