name: periocron
version: "0"
synopsis: Periodical cron
description: ...
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

library:
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - base-compat
    - clock
    - ekg-core
    - futurice-prelude
    - lens
    - lifted-async
    - lifted-base
    - monad-logger
    - mtl
    - stm
    - text
    - time
    - transformers
