name: sms-proxy
version: "0"
synopsis: SMS Proxy
description: Make an sms-proxy of everything
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - aeson-compat
    - aeson-extra
    - base-compat
    - env-config
    - futurice-prelude
    - futurice-servant
    - http-client
    - http-client-tls
    - http-types
    - servant-server
    - text

executables:
  sms-proxy-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - sms-proxy
