name: flowdock-cli
version: "0"
synopsis: Example cli tool for flowdock-rest
description: Example cli tool for flowdock-rest
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-flowdock-cli
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.10
  - base-compat
  - aeson
  - aeson-pretty
  - ansi-pretty
  - base64-bytestring
  - bytestring
  - deepseq
  - directory
  - exceptions
  - hashable >= 1.2
  - http-client
  - http-client-tls
  - lens
  - monad-http
  - tagged
  - text
  - optparse-applicative
  - transformers
  - flowdock-rest >= 0.1

executables:
  flowdock-cli:
    main: Main.hs
    source-dirs: src
