name: fum-client
version: 0.1.0.0
synopsis: FUM REST API
description: |
  Bindings to <https://github.com/futurice/futurice-ldap-user-manager FUM API>.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-fum-client
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

flags:
  aeson-compat:
    default: True
    manual: False

dependencies:
  - base                  >=4.7       && <4.10
  - aeson                 >=0.8.0.2   && <0.12
  - base-compat           >=0.6.0     && <0.10
  - constraints
  - deepseq               >=1.3.0.2   && <1.5
  - deepseq-generics      >=0.1.1.2   && <0.3
  - futurice-prelude
  - mtl                   >=2.1.3.1   && <2.3
  - monad-http            >=0.1.0.0
  - hashable              >=1.2.3.3   && <1.3
  - http-client           >=0.4.18.1  && <0.5
  - http-client-tls       >=0.2.2     && <0.3
  - lens                  >=4.7.0.1   && <4.15
  - strict-base-types     >=0.4.0     && <0.6
  - text                  >=1.2.0.6   && <1.3
  - vector                >=0.10.12.3 && <0.12

when:
  - condition: flag(aeson-compat)
    dependencies:
    - aeson-compat          >=0.3       && <0.4
  - condition: "!flag(aeson-compat)"
    dependencies:
    - aeson-extra           >=0.2.2     && <0.3

library:
  source-dirs: src
