name: fum-client
version: "0"
synopsis: FUM REST API
description: |
  Bindings to <https://github.com/futurice/futurice-ldap-user-manager FUM API>.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - aeson                 >=0.8.0.2   && <1.2
  - aeson-compat          >=0.3.5.1   && <0.4
  - base                  >=4.7       && <4.10
  - base-compat           >=0.6.0     && <0.10
  - cassava               >=0.4.5.0   && <0.5
  - constraints           >=0.8       && <0.10
  - deepseq               >=1.3.0.2   && <1.5
  - deepseq-generics      >=0.1.1.2   && <0.3
  - futurice-prelude
  - hashable              >=1.2.3.3   && <1.3
  - http-api-data
  - http-client           >=0.4.31.1  && <0.6
  - http-client-tls       >=0.2.2     && <0.4
  - lens                  >=4.7.0.1   && <4.16
  - monad-http            >=0.2.0.0   && <0.3
  - mtl                   >=2.1.3.1   && <2.3
  - postgresql-simple
  - QuickCheck
  - strict-base-types     >=0.4.0     && <0.6
  - swagger2              >=2.1.3     && <2.2
  - text                  >=1.2.0.6   && <1.3
  - vector                >=0.10.12.3 && <0.13

library:
  source-dirs: src
