name: fum-client
version: "0"
synopsis: FUM REST API
description: |
  Bindings to <https://github.com/futurice/futurice-ldap-user-manager FUM API>.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base >=4.7       && <5
  - aeson
  - aeson-compat
  - base-compat
  - cassava
  - constraints
  - deepseq
  - deepseq-generics
  - env-config
  - fum-types
  - futurice-prelude
  - hashable
  - http-api-data
  - http-client
  - http-client-tls
  - lens
  - monad-http
  - mtl
  - postgresql-simple
  - QuickCheck
  - strict-base-types
  - swagger2
  - text
  - vector

library:
  source-dirs: src
  other-modules: []
