name: servant-cache
version: 0.2.0.0
synopsis: Servant cache
description: Cache servant API endpoints
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-servant-cache
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base            >=4.7      && <4.10
  - base-compat     >=0.6.0    && <0.10
  - blaze-builder   >=0.4.0.1  && <0.5
  - bytestring      >=0.10.4.0 && <0.11
  - hashable        >=1.2.3.3  && <1.3
  - http-types      >=0.8.6    && <0.10
  - servant         >=0.5      && <0.8
  - servant-docs    >=0.5      && <0.8
  - servant-server  >=0.5      && <0.8
  - stm             >=2.4.4    && <2.5
  - stm-containers  >=0.2.9    && <0.3
  - tagged          >=0.7.3    && <0.9
  - time            >=1.4.2    && <1.7
  - wai             >=3.0.3.0  && <3.3
  - async
  - either
  - transformers
  - transformers-compat
  - monad-control
  - transformers-base
  - list-t
  - futurice-prelude

library:
  source-dirs: src

tests:
  example:
    main: Main.hs
    source-dirs: example
    dependencies:
      - servant-cache
      - servant-lucid >=0.5 && <0.8
      - lucid
      - text
      - warp

  unit-tests:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
      - servant-cache
      - tasty
      - tasty-hunit
