name: favicon-app
version: "0"
synopsis: Generate Futurice favicons
description: Fancy icons!
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/favicon-app
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

dependencies:
- base >=4.7 && <4.10
- JuicyPixels
- base-compat
- env-config
- futurice-logo
- futurice-prelude
- futurice-servant
- lens
- lucid
- semigroups
- servant
- servant-JuicyPixels
- servant-server
- servant-status
- stm
- text
- time
- transformers
- transformers-compat

executables:
  favicon:
    main: Main.hs
    ghc-options: -threaded -rtsopts
    source-dirs: src/
