name: favicon-app
version: "0"
synopsis: Generate Futurice favicons
description: Fancy icons!
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/favicon-app
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >=4.7 && <4.10
- JuicyPixels
- base-compat
- env-config
- futulogo
- futurice-prelude
- futurice-servant
- lens
- lucid
- semigroups
- servant
- servant-JuicyPixels
- servant-server
- servant-status
- stm
- text
- time
- transformers
- transformers-compat

executables:
  favicon:
    main: Main.hs
    ghc-options: -threaded
    source-dirs: src/
