name: haxl-fxtra
version: "0"
synopsis: Futurice extras for Haxl
description: |
  Mostly bindings to various datasources
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-haxl-fxtra
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base                  >=4.7      && <4.10
  - haxl
  - http-client
  - http-client-tls
  - text
  - hashable
  - parallel-io
  - github
  - fum-client
  - futurice-prelude
  - flowdock-rest         >=0.2.0.0
  - bytestring
  - exceptions
  - vector
  - bifunctors
  - tagged
  - haxl-typed
  - aeson

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
