name: haxl-fxtra
version: "0"
synopsis: Futurice extras for Haxl
description: |
  Mostly bindings to various datasources
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-haxl-fxtra
category: Web
tested-with: GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall
# http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
when:
  condition: os(linux)
  ghc-options: -optl-fuse-ld=gold
  ld-options:  -fuse-ld=gold

dependencies:
  - base                  >=4.7      && <4.10
  - aeson
  - bifunctors
  - bytestring
  - exceptions
  - flowdock-rest         >=0.2.0.0
  - fum-client
  - futurice-prelude
  - github
  - hashable
  - haxl
  - http-client
  - http-client-tls
  - parallel-io
  - tagged
  - text
  - vector

library:
  source-dirs: src
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
