name: spice-stats
version: 0.0.0.0
synopsis: Realm of Chilicorn
description: OmgLolKek
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-spice-stats
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.10
  - aeson
  - aeson-pretty
  - ansi-pretty
  - base64-bytestring
  - bifunctors
  - binary-orphans
  - binary-tagged
  - blaze-html
  - bytestring
  - case-insensitive
  - deepseq
  - directory
  - either
  - env-config
  - exceptions
  - filepath
  - flowdock-rest
  - futulogo
  - futurice-prelude
  - futurice-servant
  - github
  - gitrev
  - hashable >= 1.2
  - http-client
  - http-client-tls
  - http-types
  - lens
  - markdown
  - optparse-applicative
  - regex-applicative
  - regex-applicative-text
  - regex-compat
  - semigroups
  - servant >=0.6 && <0.8
  - servant-server
  - SHA
  - stm
  - tagged
  - text
  - transformers
  - transformers-compat
  - unordered-containers
  - vector
  - wai
  - warp

library:
  source-dirs: src

executables:
  spice-stats:
    main: Main.hs
    source-dirs: cli
    dependencies:
      - spice-stats
  spice-stats-server:
    main: Main.hs
    source-dirs: srv
    ghc-options: -Wall -threaded
    dependencies:
      - spice-stats
