name: personio-client
version: "0"
synopsis: Personio client library
description: |
  Bindings to <https://www.personio.de/de/api-documentation/>
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - aeson
  - aeson-compat
  - base
  - constraints
  - env-config
  - futurice-prelude
  - http-api-data
  - http-client
  - monad-http
  - swagger2
  - text
  - time

library:
  source-dirs: src

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: tests/
    dependencies:
      - file-embed
      - personio-client
      - tasty
      - tasty-quickcheck
      - tasty-hunit
